# Generated by Django 2.1.7 on 2019-04-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ('order',), 'verbose_name': 'Item de F.A.Q', 'verbose_name_plural': 'Items de F.A.Q'},
        ),
    ]
