# Generated by Django 2.1.5 on 2019-01-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_questionnaire_description_max'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ('questionnaire', 'order'), 'verbose_name': 'Thème', 'verbose_name_plural': 'Thèmes'},
        ),
        migrations.AddField(
            model_name='theme',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
