# Generated by Django 2.1.5 on 2019-01-09 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0014_add_timestamp_on_response_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsefile',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='response_files', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
