# Generated by Django 2.1.7 on 2019-03-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_copy_existing_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_directory_name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Login sur l'active directory de la cour"),
        ),
    ]
