# Generated by Django 2.1.7 on 2019-05-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0007_remove_userprofile_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('audited', 'Organisme Contrôlé'), ('inspector', 'Contrôleur')], max_length=255),
        ),
    ]
