# Generated by Django 2.1.7 on 2019-05-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0008_change_meta_on_profile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='active_directory_name',
        ),
    ]
