# Generated by Django 2.1.7 on 2019-06-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0009_remove_userprofile_active_directory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('audited', 'Organisme interrogé'), ('inspector', 'Contrôleur')], max_length=255),
        ),
    ]
