# Generated by Django 2.1.7 on 2019-05-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0009_remove_userprofile_active_directory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_directory_name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Login sur l'active directory de la cour"),
        ),
    ]
