# Generated by Django 2.2.11 on 2020-06-09 14:44

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0013_organization_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=fernet_fields.fields.EncryptedEmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=fernet_fields.fields.EncryptedCharField(default='', max_length=255, verbose_name='prénom'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=fernet_fields.fields.EncryptedCharField(default='', max_length=255, verbose_name='nom'),
        ),
    ]
