# Generated by Django 2.2.11 on 2020-06-09 14:44

from django.db import migrations


def migrate_user_data_to_encrypted_fields(apps, schema_editor):
    UserProfile = apps.get_model('user_profiles', 'UserProfile')
    for profile in UserProfile.objects.all():
        profile.first_name = profile.user.first_name
        profile.last_name = profile.user.last_name
        profile.email = profile.user.email
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0014_add_encrypted_user_data'),
    ]

    operations = [
        migrations.RunPython(migrate_user_data_to_encrypted_fields, migrations.RunPython.noop),
    ]
