# Generated by Django 2.2.13 on 2021-04-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0014_useripaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useripaddress',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
