# Generated by Django 2.1.4 on 2018-12-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_remove_theme_reference_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='reference_code',
        ),
    ]
