# Generated by Django 2.1.4 on 2018-12-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_remove_questionnaire_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
