# Generated by Django 2.1.5 on 2019-01-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_add_order_to_theme'),
    ]

    operations = [
    ]
