# Generated by Django 2.1.5 on 2019-01-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_remove_mptt_on_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'ordering': ('control', 'order'), 'verbose_name': 'Questionnaire', 'verbose_name_plural': 'Questionnaires'},
        ),
    ]
