# Generated by Django 2.1.5 on 2019-01-11 00:10

import control.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_change_question_fle_meta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='file',
            field=models.FileField(default='', upload_to=control.upload_path.questionnaire_file_path, verbose_name='fichier'),
            preserve_default=False,
        ),
    ]
