# Generated by Django 2.1.5 on 2019-01-11 01:45

import control.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0019_questionnaire_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=control.upload_path.questionnaire_file_path, verbose_name='fichier'),
        ),
    ]
