# Generated by Django 2.1.7 on 2019-03-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0021_questionnaire_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date de réponse souhaitée', null=True, verbose_name='échéance'),
        ),
    ]
