# Generated by Django 2.1.7 on 2019-06-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0023_auto_20190523_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Ce questionnaire est-il encore au stade de brouillon?', verbose_name='brouillon'),
        ),
    ]
