# Generated by Django 2.1.7 on 2019-06-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0024_remove-readonly-on-order-field'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Ce questionnaire est-il encore au stade de brouillon?', verbose_name='brouillon'),
        ),
    ]
