# Generated by Django 2.1.7 on 2019-06-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0025_questionnaire_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='is_draft',
            field=models.BooleanField(blank=True, default=False, help_text='Ce questionnaire est-il encore au stade de brouillon?', null=True, verbose_name='brouillon'),
        ),
    ]
