# Generated by Django 2.1.9 on 2019-07-10 12:20

import control.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0025_questionnaire_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='generated_file',
            field=models.FileField(blank=True, null=True, upload_to=control.upload_path.questionnaire_file_path, verbose_name='fichier généré automatiquement'),
        ),
    ]
