# Generated by Django 2.1.9 on 2019-07-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0027_update_help_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='file',
            new_name='uploaded_file',
        ),
    ]
