# Generated by Django 2.1.9 on 2019-07-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0030_auto_20190715_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='reference_code',
            field=models.CharField(blank=True, help_text='Ce code est utilisé notamment pour le dossier de stockage des réponses', max_length=255, unique=True, verbose_name='code de référence'),
        ),
    ]
