# Generated by Django 2.2.3 on 2019-08-12 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0033_add_is_deleted_to_responsefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='reference_code',
            field=models.CharField(error_messages={'unique': 'UNIQUE'}, help_text='Ce code est utilisé notamment pour le dossier de stockage des réponses', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='INVALID', regex='^[\\.\\s\\w-]+$')], verbose_name='code de référence'),
        ),
    ]
