# Generated by Django 2.2.5 on 2019-11-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0034_change_meta_data_on_reference_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionfile',
            options={'ordering': ('question', 'order'), 'verbose_name': 'Question: Fichier Annexe', 'verbose_name_plural': 'Question: Fichiers Annexes'},
        ),
        migrations.AlterModelOptions(
            name='responsefile',
            options={'verbose_name': 'Réponse: Fichier Déposé', 'verbose_name_plural': 'Réponse: Fichiers Déposés'},
        ),
    ]
