# Generated by Django 2.2.5 on 2019-11-05 13:23

from django.db import migrations

from actstream import registry


def find_questionnaire_creator(questionnaire):
    creation_action = questionnaire.action_object_actions.filter(
        verb='created questionnaire').first()
    if not creation_action:
        return None
    return creation_action.actor_object_id


def set_editor_to_questionnaire_creator(apps, schema_editor):
    Questionnaire = apps.get_model('control', 'Questionnaire')
    registry.register(apps.get_model('control.Questionnaire'))
    for questionnaire in Questionnaire.objects.all():
        creator_id = find_questionnaire_creator(questionnaire)
        questionnaire.editor_id = creator_id
        questionnaire.save()


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0036_questionnaire_editor'),
    ]

    operations = [
        migrations.RunPython(
            set_editor_to_questionnaire_creator, reverse_code=lambda apps, schema_editor: None)
    ]
