# Generated by Django 2.2.8 on 2019-12-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0037_update_questionnaire_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modifié'),
        ),
    ]
